### ISSUE TITLE
Bladerf bandwidth limited to 2 MHz

### ISSUE THREAD

**Issue by andruxa-smirnov** [BatchDrake/SigDigger#13]
When i set bladerf bandwidth more, than 2MHz (more 2000000 samples per second), bandwidth all time limited to 2 MHz.

**Comment by BatchDrake** [comment]
Confirmed, working on it.

**Comment by BatchDrake** [comment]
I've just commited something to suscan's master branch that may be related to what you are experiencing. I've just checked it out with AirSpy at 6000000 and Bandwidth is limited to 6 MHz (as expected). Rebuild suscan from master and try again. If you still fail to make it work, could you provide a screenshot?

**Comment by andruxa-smirnov** [comment]
Rebuilding don't solve problem
![2019-08-23 22-01-34](https://user-images.githubusercontent.com/5259697/63617356-efa6ff80-c5f1-11e9-95e0-e6eb844d9d61.png)

**Comment by BatchDrake** [comment]
That's strange, I can increase the bandwidth up to the sample rate. Can you
provide some screenshots of what you're attempting?

**Comment by andruxa-smirnov** [comment]
![2019-08-24 09-34-09](https://user-images.githubusercontent.com/5259697/63633514-81465980-c652-11e9-9943-e13b5ac93b48.png)
![2019-08-24 09-34-42](https://user-images.githubusercontent.com/5259697/63633517-886d6780-c652-11e9-9e6d-43f9483dc16e.png)

**Comment by BatchDrake** [comment]
You are not running the latest version of SigDigger (there should be a bandwidth control in the source panel). Pull from master (from SigDigger, not Suscan) and build again. You should be able to adjust the bandwidth dynamically after that.

**Comment by andruxa-smirnov** [comment]
What i doing not so?
I deleted SigDigger folder. I clone master branch newly, after that i do "qmake", "make" and "sudo make install", but that don't solve problem.
More one intresting thing - i see bladerf device double in sdr sources list. Why?

**Comment by BatchDrake** [comment]
I've just cloned SigDigger from master. After building I do see the bandwidth adjust widget, look:

![Captura de pantalla de 2019-08-24 18-21-55](https://user-images.githubusercontent.com/610895/63640068-4f59e500-c69c-11e9-8997-0854733d1957.png)

Please check again whether you are actually running the right executable. This dynamic bandwidth control feature is already in master.

> More one intresting thing - i see bladerf device double in sdr sources list. Why?

This happens if the device label has changed since the last time you plugged it (or if you have two different BladeRF devices, and the one you plugged last time is different from the one you have plugged now). This is the expected behavior. What is not expected is the BladeRF identification string to change between executions.
