### ISSUE TITLE
add a "custom" sdr option

### ISSUE THREAD

**Issue by n0p** [BatchDrake/SigDigger#173]
so we can specify the options to soapySDR like "driver=uhd,addr=192.168.1.12"

**Comment by BatchDrake** [comment]
You can already do that:

- Go to profile settings, select SDR and any device (Dummy is fine)
- Open device specific tweaks
- Change the driver to `uhd` and/or other parameters
- Click OK and start the SDR

Of course this assumes that `uhd` is something supported by your current SoapySDR installation, otherwise it will fail.
