### ISSUE TITLE
Feature request: load last values

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#21]
I know that profiles can be saved and loaded, but I think it would be very convenient if the last entered data for frequency and sampling rate are set every-time that app runs. What do you think?

**Comment by BatchDrake** [comment]
Indeed, that's the expected behavior. Profiles are just a way to store source configurations that are used frequently. 

That configuration should be saved in and restored from `~/.suscan/config/uiconfig.xml`. If it's not the case, something is going wrong.

PS: I'm filing this as a bug with a new tag (macos). This is probably a porability issue and it will make sense to address this within the context of the upcoming Mac support.
